# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f612b88d855f31430a9d923cbcd3c925c24c68e24be117fda7520cd7c935e21298ff048f9f5ec7a0a6eb8c82eac58a5e4225224de3e19e967e9ef9a20f999d80

test:
  secret_key_base: 071a908079c651249d99ef7d02b51169c5b6d53aec9937252746bc9b77f4a1856ec23e2a3acba4f036bff9eac4e7cfb968b823d5c1b24dc2c39bc0e34b63969c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
